apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example
spec:
  collectors:
    - logs:
        selector:
          - app=rook-ceph-operator
        namespace: openshift-storage
        limits:
          #maxAge: 30d
          maxLines: 100
    - exec:
        name: rook-ceph-tools
        selector:
          - app=rook-ceph-tools
        namespace: openshift-storage
        command: ["osd tree"]
        #args: ["osd tree"]
        timeout: 120s
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.16.0"
              message: The application requires at least Kubernetes 1.16.0 or later
              uri: https://kubernetes.io
          - warn:
              when: "< 1.17.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.17.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - customResourceDefinition:
        customResourceDefinitionName: storageclusters.ocs.openshift.io
        outcomes:
          - fail:
              message: The storageclusters.ocs.openshift.io CRD was not found in the cluster.
          - pass:
              message: OCS is installed and available.
    - storageClass:
        checkName: Required storage classes
        storageClassName: "ocs-storagecluster-ceph-rbd"
        outcomes:
          - fail:
              message: The ocs-storagecluster-ceph-rbd storage class was not found
          - pass:
              message: All good on storage classes
    - nodeResources:
        checkName: Must have at least 3 nodes in the cluster
        outcomes:
          - fail:
              when: "count() < 3"
              message: This application requires at least 3 nodes
          - warn:
              when: "count() < 5"
              message: This application recommends at last 5 nodes.
          - pass:
              message: This cluster has enough nodes.
    - nodeResources:
        checkName: Total CPU Cores in the cluster is 4 or greater
        outcomes:
        - fail:
            when: "sum(cpuCapacity) < 4"
            message: The cluster must contain at least 4 cores
        - pass:
            message: There are at least 4 cores in the cluster
    - nodeResources:
        checkName: Each node must have at least 40 GB of ephemeral storage
        outcomes:
        - fail:
            when: "min(ephemeralStorageCapacity) < 40Gi"
            message: Noees in this cluster do not have at least 40 GB of ephemeral storage.
            uri: https://kurl.sh/docs/install-with-kurl/system-requirements
        - warn:
            when: "min(ephemeralStorageCapacity) < 100Gi"
            message: Nodes in this cluster are recommended to have at least 100 GB of ephemeral storage.
            uri: https://kurl.sh/docs/install-with-kurl/system-requirements
        - pass:
            message: The nodes in this cluster have enough ephemeral storage.
    - deploymentStatus:
        name: csi-rbdplugin-provisioner
        namespace: openshift-storage
        outcomes:
          - fail:
              when: "< 1"
              message: The csi-rbdplugin-provisioner deployment in namespace openshift-storage does not have any ready replicas.
          - warn:
              when: "= 1"
              message: The csi-rbdplugin-provisioner deployment in namespace openshift-storage has only a single ready replica.
          - pass:
              message: There are multiple ready replicas of the csi-rbdplugin-provisioner deployment in namespace openshift-storage.
